### ISSUE TITLE
[게임오브젝트/계층] 3D 오브젝트를 활용하여 간단한 구조물(예: 원두막 등)을 FPSController의 스케일에 부합하게 만들 수 있는가?

### ISSUE THREAD

**Issue by yeonju52** [FALL2022-CG/End_of_the_Earth#10]
#### 1. 3D 오브젝트를 활용하여 간단한 구조물(예: 원두막 등)을 FPSController의 스케일에 부합하게 만들 수 있는가? 

2. Prefab을 만들 수 있는가?

**Comment by eunsangeun** [comment]
undersea 신전(structure) 사용함
